#!/usr/bin/env bash
# Stamp a unique CFBundleVersion (CURRENT_PROJECT_VERSION) for every iOS build.
# Marketing version stays in Config/MarketingVersion.xcconfig (starts at 1.0.0).
#
# Priority for build number:
#   1. MEKASA_BUILD_NUMBER env (explicit override)
#   2. GITHUB_RUN_NUMBER (CI)
#   3. Monotonic integer: max(git-commit-count, last-generated) + 1 for local
#
# Usage:
#   ./scripts/ensure_unique_build_number.sh
#   ./scripts/ensure_unique_build_number.sh --stamp-plist /path/to/Info.plist
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_DIR="${ROOT}/Config"
OUT="${CONFIG_DIR}/GeneratedBuild.xcconfig"
STATE="${CONFIG_DIR}/.last_build_number"
STAMP_PLIST=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stamp-plist)
      STAMP_PLIST="${2:-}"
      shift 2
      ;;
    *)
      echo "usage: $0 [--stamp-plist Info.plist]" >&2
      exit 1
      ;;
  esac
done

mkdir -p "${CONFIG_DIR}"

marketing="$(
  awk -F'=' '/^MARKETING_VERSION/ {
    gsub(/[[:space:]]/, "", $2); print $2; exit
  }' "${CONFIG_DIR}/MarketingVersion.xcconfig" 2>/dev/null || true
)"
marketing="${marketing:-1.0.0}"

if [[ -n "${MEKASA_BUILD_NUMBER:-}" ]]; then
  build="${MEKASA_BUILD_NUMBER}"
elif [[ -n "${GITHUB_RUN_NUMBER:-}" ]]; then
  build="${GITHUB_RUN_NUMBER}"
else
  git_count="$(git -C "${ROOT}/.." rev-list --count HEAD 2>/dev/null || echo 0)"
  last=0
  if [[ -f "${STATE}" ]]; then
    last="$(tr -cd '0-9' < "${STATE}" || true)"
    last="${last:-0}"
  fi
  if [[ -f "${OUT}" ]]; then
    prev="$(awk -F'=' '/^CURRENT_PROJECT_VERSION/ {
      gsub(/[[:space:]]/, "", $2); print $2; exit
    }' "${OUT}" || true)"
    prev="${prev:-0}"
    if [[ "${prev}" =~ ^[0-9]+$ ]] && (( prev > last )); then
      last="${prev}"
    fi
  fi
  build=$(( git_count > last ? git_count : last ))
  build=$(( build + 1 ))
fi

if ! [[ "${build}" =~ ^[0-9]+([.][0-9]+)*$ ]]; then
  echo "error: invalid build number '${build}'" >&2
  exit 1
fi

cat > "${OUT}" <<EOF
// Auto-generated by scripts/ensure_unique_build_number.sh — do not edit or commit.
CURRENT_PROJECT_VERSION = ${build}
EOF

printf '%s\n' "${build}" > "${STATE}"

if [[ -n "${STAMP_PLIST}" ]]; then
  if [[ ! -f "${STAMP_PLIST}" ]]; then
    echo "warning: Info.plist not found at ${STAMP_PLIST} (skipping stamp)" >&2
  else
    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${marketing}" "${STAMP_PLIST}" 2>/dev/null \
      || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${marketing}" "${STAMP_PLIST}"
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${build}" "${STAMP_PLIST}" 2>/dev/null \
      || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${build}" "${STAMP_PLIST}"
    echo "Stamped ${STAMP_PLIST} → ${marketing} (${build})"
  fi
fi

echo "Mekasa version ${marketing} (${build})"
