#!/usr/bin/env bash
# Sync Google Sign-In URL scheme from GoogleService-Info.plist into xcconfig.
# Run after downloading a real Firebase plist (or leave as no-op if missing).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLIST="${ROOT}/Mekasa/GoogleService-Info.plist"
OUT="${ROOT}/Config/GoogleSignIn.xcconfig"

if [[ ! -f "$PLIST" ]]; then
  cat > "$OUT" <<'EOF'
// Auto-generated by scripts/sync_google_signin_config.sh
// Missing Mekasa/GoogleService-Info.plist — Google Sign-In URL scheme unset.
GOOGLE_REVERSED_CLIENT_ID =
EOF
  echo "[mekasa] No GoogleService-Info.plist yet → wrote empty GoogleSignIn.xcconfig"
  exit 0
fi

# Prefer /usr/libexec/PlistBuddy (macOS); fall back to plutil.
reversed=""
if [[ -x /usr/libexec/PlistBuddy ]]; then
  reversed="$(/usr/libexec/PlistBuddy -c 'Print :REVERSED_CLIENT_ID' "$PLIST" 2>/dev/null || true)"
elif command -v plutil >/dev/null 2>&1; then
  reversed="$(plutil -extract REVERSED_CLIENT_ID raw -o - "$PLIST" 2>/dev/null || true)"
fi

client=""
if [[ -x /usr/libexec/PlistBuddy ]]; then
  client="$(/usr/libexec/PlistBuddy -c 'Print :CLIENT_ID' "$PLIST" 2>/dev/null || true)"
elif command -v plutil >/dev/null 2>&1; then
  client="$(plutil -extract CLIENT_ID raw -o - "$PLIST" 2>/dev/null || true)"
fi

if [[ -z "$reversed" || "$reversed" == *"Does Not Exist"* ]]; then
  cat > "$OUT" <<'EOF'
// Auto-generated by scripts/sync_google_signin_config.sh
// GoogleService-Info.plist has no REVERSED_CLIENT_ID.
// Enable Google in Firebase Auth, re-download the plist, re-run this script.
GOOGLE_REVERSED_CLIENT_ID =
EOF
  echo "[mekasa] WARNING: plist missing REVERSED_CLIENT_ID (enable Google Sign-In in Firebase)"
  exit 0
fi

cat > "$OUT" <<EOF
// Auto-generated by scripts/sync_google_signin_config.sh — do not commit.
// CLIENT_ID=${client}
GOOGLE_REVERSED_CLIENT_ID = ${reversed}
EOF

echo "[mekasa] Google Sign-In URL scheme → ${reversed}"
