#!/usr/bin/env bash
# Sync Google Sign-In URL scheme from GoogleService-Info.plist into:
#   1) Config/GoogleSignIn.xcconfig
#   2) Mekasa/Info.plist (literal scheme — Xcode often does not expand $(VAR) in URL schemes)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIREBASE_PLIST="${ROOT}/Mekasa/GoogleService-Info.plist"
INFO_PLIST="${ROOT}/Mekasa/Info.plist"
OUT="${ROOT}/Config/GoogleSignIn.xcconfig"
PB=/usr/libexec/PlistBuddy

read_key() {
  local key="$1"
  if [[ -x "$PB" ]]; then
    "$PB" -c "Print :${key}" "$FIREBASE_PLIST" 2>/dev/null || true
  elif command -v plutil >/dev/null 2>&1; then
    plutil -extract "$key" raw -o - "$FIREBASE_PLIST" 2>/dev/null || true
  fi
}

set_info_scheme() {
  local scheme="$1"
  [[ -f "$INFO_PLIST" ]] || return 0
  [[ -x "$PB" ]] || return 0

  # Ensure CFBundleURLTypes exists
  "$PB" -c 'Print :CFBundleURLTypes' "$INFO_PLIST" >/dev/null 2>&1 \
    || "$PB" -c 'Add :CFBundleURLTypes array' "$INFO_PLIST"

  local count
  count="$("$PB" -c 'Print :CFBundleURLTypes:' "$INFO_PLIST" 2>/dev/null | grep -c 'Dict' || true)"
  # Prefer finding existing GoogleSignIn entry by name
  local idx=""
  local i=0
  while true; do
    local name
    name="$("$PB" -c "Print :CFBundleURLTypes:${i}:CFBundleURLName" "$INFO_PLIST" 2>/dev/null || true)"
    [[ -z "$name" ]] && break
    if [[ "$name" == "GoogleSignIn" ]]; then
      idx="$i"
      break
    fi
    i=$((i + 1))
  done

  if [[ -z "$idx" ]]; then
    "$PB" -c 'Add :CFBundleURLTypes: dict' "$INFO_PLIST"
    idx="$i"
    "$PB" -c "Add :CFBundleURLTypes:${idx}:CFBundleURLName string GoogleSignIn" "$INFO_PLIST"
    "$PB" -c "Add :CFBundleURLTypes:${idx}:CFBundleURLSchemes array" "$INFO_PLIST"
    "$PB" -c "Add :CFBundleURLTypes:${idx}:CFBundleURLSchemes:0 string ${scheme}" "$INFO_PLIST"
  else
    # Replace schemes array with the single reversed client id
    "$PB" -c "Delete :CFBundleURLTypes:${idx}:CFBundleURLSchemes" "$INFO_PLIST" 2>/dev/null || true
    "$PB" -c "Add :CFBundleURLTypes:${idx}:CFBundleURLSchemes array" "$INFO_PLIST"
    "$PB" -c "Add :CFBundleURLTypes:${idx}:CFBundleURLSchemes:0 string ${scheme}" "$INFO_PLIST"
  fi
}

if [[ ! -f "$FIREBASE_PLIST" ]]; then
  reversed="com.googleusercontent.apps.934775015882-tkn8jri65ijtbadhlkpskdo3j2nh0m0t"
  cat > "$OUT" <<EOF
// Auto-generated by scripts/sync_google_signin_config.sh
// Missing Mekasa/GoogleService-Info.plist — using project default Google URL scheme.
GOOGLE_REVERSED_CLIENT_ID = ${reversed}
EOF
  set_info_scheme "$reversed"
  echo "[mekasa] No GoogleService-Info.plist yet → wrote default Google URL scheme"
  exit 0
fi

reversed="$(read_key REVERSED_CLIENT_ID)"
client="$(read_key CLIENT_ID)"

if [[ -z "$reversed" || "$reversed" == *"Does Not Exist"* ]]; then
  # Known Mekasa iOS OAuth reverse client id (hackathon2025-472017).
  reversed="com.googleusercontent.apps.934775015882-tkn8jri65ijtbadhlkpskdo3j2nh0m0t"
  echo "[mekasa] WARNING: plist missing REVERSED_CLIENT_ID — using project default scheme"
fi

cat > "$OUT" <<EOF
// Auto-generated by scripts/sync_google_signin_config.sh — do not commit.
// CLIENT_ID=${client}
GOOGLE_REVERSED_CLIENT_ID = ${reversed}
EOF

set_info_scheme "$reversed"

echo "[mekasa] Google Sign-In URL scheme → ${reversed}"
echo "[mekasa] Wrote Config/GoogleSignIn.xcconfig and Mekasa/Info.plist"
